# Generated by Django 4.1.3 on 2022-11-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('Recibido por Conserje', 'Recibido por Conserje'), ('Entregado', 'Entregado')], max_length=50),
        ),
    ]
